services:
  base:
    build:
      #ruta a través de la cual desde cualquier proyecto
      #se tiene aceeso a cualquier imagen (DFile), recurso
      context: /home/morgado/devops/DespAW/Docker/Caronte
      dockerfile: ./dockerfiles/base/ubuntu/Dockerfile
    container_name: ctbaseDAW